// <auto-generated />
namespace Webtcgg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update1512 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update1512));
        
        string IMigrationMetadata.Id
        {
            get { return "202412150922005_update1512"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
